---
url_sso_aws: https://sso.jumpcloud.com/saml2/aws
outputformat: json
path_file: ~/.aws
filename: credentials
default_region: us-east-1
regions:
  - id: us-east-1
    name: US East (N. Virginia)
  - id: us-east-2
    name: US East (Ohio)
  - id: us-west-1
    name: US West (N. California)
  - id: us-west-2
    name: US West (Oregon)
  - id: ca-central-1
    name: Canada (Central)
  - id: eu-west-1
    name: EU (Ireland)
  - id: eu-central-1
    name: EU (Frankfurt)
  - id: eu-west-2
    name: EU (London)
  - id: ap-northeast-1
    name: Asia Pacific (Tokyo)
  - id: ap-northeast-2
    name: Asia Pacific (Seoul)
  - id: ap-southeast-1
    name: Asia Pacific (Singapore)
  - id: ap-southeast-2
    name: Asia Pacific (Sydney)
  - id: ap-south-1
    name: Asia Pacific (Mumbai)
  - id: sa-east-1
    name: South America (São Paulo)
